FROM node:20-alpine

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY . .

RUN npm install --force

RUN npx prisma generate --schema=packages/database/schema.prisma

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=development
ENV PATH="/app/node_modules/.bin:${PATH}"

CMD ["sh", "-c", "next dev --port 3000 --hostname 0.0.0.0"]